# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-objectivec' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sample-objectivec
  pod 'Batch', '~>1.9'

  target 'sample-objectivecTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
