name: Documentation

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build DocC
        run: |
            # Build DocArchive
            cd Sources && xcodebuild docbuild -scheme Batch -derivedDataPath ./BatchBuild
            
            # Transform for static hosting
            `xcrun -find docc` process-archive transform-for-static-hosting  ./BatchBuild/Build/Products/Debug-maccatalyst/Batch.doccarchive --hosting-base-path Batch-iOS-SDK --output-path ../docs
     
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
